### PR TITLE
dirent: Remove non-standard dirent types enum

### PR DESCRIPTION
**Pull request by agkaminski**
JIRA: RTOS-603

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [x] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [x] This PR needs additional PRs to work (https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/106 and https://github.com/phoenix-rtos/phoenix-rtos-ports/pull/67).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by nalajcie** [comment]
There is an error in `dummyfs` also - it returns `ot*` enums as a dirent types (it was working previously because value of otXX == dtXX) - probably worth fixing at the same time to fully resolve the issue.

Other than that - LGTM.

**Comment by agkaminski** [comment]
@nalajcie Haven't noticed that, thanks, will fix. I simply was searching for dt* usages

**Comment by lukileczo** [comment]
If I understand correctly, also `imxrt-multi` uses `ot*` enums to communicate with `dummyfs`

**Review by lukileczo — APPROVED** [review]

**Review by badochov — APPROVED** [review]
LGTM

**Pull request merged**
