### PR TITLE
Fix wrong mask value in ioctl.h

### PR DESCRIPTION
**Pull request by adamdebek**
JIRA: RTOS-476

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by adamdebek** [comment]
First 2 most significant bits indicate read/write followed by 14 size bits, but musk is only 13 bits.

**Comment by nalajcie** [comment]
hmm, maybe provide 2 commits: 
 - first formatting the full file as required by clang-format
 - second with the necessary fix

**Comment by agkaminski** [comment]
From what I see this stuff has been taken from openBSD and `IOCPARM_MASK` is `0x1fff` there. It makes me think this change is wrong

**Comment by adamdebek** [comment]
Yea, `IOCPARM_MASK` can remain `0x1fff` (13 bits) but then `IOC_VOID` should be `0x2000000` so `IN/OUT/VOID` information is on 3 most significant bits of request.

**Comment by agkaminski** [comment]
One commit is missing JIRA ID, you can use RTOS-374 for code formatting corrections

**Review by agkaminski — APPROVED** [review]

**Pull request merged**
