### PR TITLE
unistd/getopt.c: fix getopt() function

### PR DESCRIPTION
**Pull request by kemonats**
- added condition to check optind <= 0
 - improved handling of options --
 - for return getopt() to initial state set optind = 0

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Review by nalajcie — APPROVED** [review]
IMHO a valid fix - `newlib` and `glibc` does the same (resets internal state on `optind == 0`), also busybox sets `optind = 0` to reset `getopt` state in case of NOFORK aplets.

`--` was handled improperly (`--x` was parsed as `--`), now it's better. Still, I'm not sure how we should react to `--x` - right now we'll write `illegal option -- -` which is not really helpful :).

I would like to have these fixed code paths tested, @damianloew can You change Your `getopt test` PR test for propper `getopt` resetting and for `--x` case?

LGTM.

**Comment by damianloew** [comment]
> IMHO a valid fix - `newlib` and `glibc` does the same (resets internal state on `optind == 0`), also busybox sets `optind = 0` to reset `getopt` state in case of NOFORK aplets.
> 
> `--` was handled improperly (`--x` was parsed as `--`), now it's better. Still, I'm not sure how we should react to `--x` - right now we'll write `illegal option -- -` which is not really helpful :).
> 
> I would like to have these fixed code paths tested, @damianloew can You change Your `getopt test` PR test for propper `getopt` resetting and for `--x` case?
> 
> LGTM.

Yes, of course, I will cover it in the getopt test. Didn't tested yet, but I suppose we should set optind to 0 instead of 1 now in psh applets, like history. I can change it too.

**Comment by damianloew** [comment]
> > IMHO a valid fix - `newlib` and `glibc` does the same (resets internal state on `optind == 0`), also busybox sets `optind = 0` to reset `getopt` state in case of NOFORK aplets.
> > `--` was handled improperly (`--x` was parsed as `--`), now it's better. Still, I'm not sure how we should react to `--x` - right now we'll write `illegal option -- -` which is not really helpful :).
> > I would like to have these fixed code paths tested, @damianloew can You change Your `getopt test` PR test for propper `getopt` resetting and for `--x` case?
> > LGTM.
> 
> Yes, of course, I will cover it in the getopt test. Didn't tested yet, but I suppose we should set optind to 0 instead of 1 now in psh applets, like history. I can change it too.

Yeah, I verified that this PR and setting optind to 0 in pshaapp resolves the #208 #521 issue :)

**Comment by damianloew** [comment]
> 

About `--x`, it works the same on host:
Screenshot from 2022-10-10 17-00-06

I've added new test cases (the link below) and it seems that after adding changes from this PR our `getopt` will be POSIX compilant :)

https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/139

**Pull request merged**
