### PR TITLE
math: Fix sqrt calc on IA32

### PR DESCRIPTION
**Pull request by gerard5**
This change assumes that the `fsqrt` calculation is performed for double precision FP and rounded to the nearest (even) value. To achieve this, the FPU control word is set accordingly at the sqrt computation time. ~~All exceptions are enabled: any underflow, overflow, /0, invalid precission, etc during sqrt calculation will throw an exception.~~
All other settings (exceptions mask, infinity control) in FPU control word are inherited (not changed).

Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/800

JIRA: RTOS-562

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: ia32-generic.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Review by adamdebek — DISMISSED** [review]
LGTM, passed my sqrt tests, which soon will be in review

**Comment by kemonats** [comment]
Small comment.
From the documentation:
## Intel® 64 and IA-32 Architectures Software Developer’s Manual Volume 1: Basic Architecture

### 8.1.5.1  x87 FPU Floating-Point Exception Mask Bits
The exception-flag mask bits (bits 0 through 5 of the x87 FPU control word) mask the 6 floating-point exception
flags in the x87 FPU status word. **When one of these mask bits is set, its corresponding x87 FPU floating-point
exception is blocked from being generated.**

**Comment by gerard5** [comment]
> Small comment. From the documentation:
> ..

You're right, in the meantime I modified this a bit: _to inherit the control word settings except the ones I want to set (RC, PC)_. This change was posted to test if it fixes the issue. I will push a patch-set regarding the changes I write about, I will be grateful if you take a look.

**Review by agkaminski — APPROVED** [review]
LGTM

**Review by adamdebek — APPROVED** [review]

**Pull request merged**
